Fix(adilhyz-repo): Installer

diff --git a/Installer b/Installer
--- a/Installer
+++ b/Installer
@@ -104,6 +104,38 @@ ${BLD}${HIJ}[${MER}!${HIJ}]${RST} ${BLD}${MER}This script does NOT have the pote
     done
 }
 
+add_adilhyz_repo() {
+    clear
+    logo "Add adilhyz custom repo"
+    repo="adilhyz-repo"
+    sleep 2
+
+    # Mensaje de instalación del repositorio
+    printf "%b\n" "${BLD}${KUN}Installing ${BRU}${repo}${KUN} repository...${RST}"
+
+    # Verificar si ya existe la sección en pacman.conf
+    if ! grep -q "\[${repo}\]" /etc/pacman.conf; then
+        # Agregar repo al final del archivo
+        if printf "\n[%s]\nSigLevel = Optional TrustAll\nServer = http://adilhyz.github.io/adilhyz-repo/x86_64\n" "$repo" \
+           | sudo tee -a /etc/pacman.conf >/dev/null 2>> "$ERROR_LOG"; then
+            printf "\n%b\n" "${BLD}${KUN}${repo} ${HIJ}repository added successfully!${RST}"
+
+            # Actualizar bases de datos
+            if ! sudo pacman -Syy 2>&1 | tee -a "$ERROR_LOG" >/dev/null; then
+                log_error "Database update failed"
+                return 1
+            fi
+        else
+            log_error "Error adding repository - check permissions"
+            return 1
+        fi
+    else
+        printf "\n%b\n" "${BLD}${KUN}The repository already exists and is configured${RST}"
+        sleep 2
+        return 0
+    fi
+}
+
 install_dependencies() {
     clear
     logo "Installing needed packages.."
@@ -388,7 +420,7 @@ install_aur() {
     logo "Installing AUR dependencies."
     sleep 2
 
-    logo "installing Yay, Paru, Adilhyz-repo (Needed), Neofetch, Cava, Fzf-tab, Cpuid"
+    logo "installing Yay, Paru, Adilhyz-repo (Needed), Fzf-tab, Cpuid"
 
     if ! command -v yay >/dev/null 2>&1; then
         printf "%s%sInstalling yay%s\n" "${BLD}" "${BRU}" "${RST}"
@@ -499,6 +531,7 @@ final_prompt() {
 # --- Main run --- #
 initial_checks
 welcome
+add_adilhyz_repo
 install_dependencies
 install_adilhyz_dependencies
 clone_dotfiles
